version: '3.8'

services:
  postgres:
    image: postgres:18.0-alpine3.21
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: simplebank
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local