spring:
  application:
    name: simplebank
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:simplebank}?currentSchema=public&reWriteBatchedInserts=true
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:1234}
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:/db/migration
    sql-migration-suffixes: sql
    baseline-on-migrate: true
    baseline-version: 0
    out-of-order: true
  hikari:
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
    maximum-pool-size: 50
    minimum-idle: 5
    connection-test-query: SELECT 1
    auto-commit: false
